async function startCircle(){const stream=await checkMedia('video');if(!stream)return;cirStream=stream;document.getElementById('circle-video').srcObject=cirStream;cirChunks=[];cirSec=0;document.getElementById('circle-timer').textContent='0:00';let mime='';const codecs=['video/webm;codecs=vp8,opus','video/webm;codecs=vp9,opus','video/webm','video/mp4;codecs=h264,aac','video/mp4'];for(const c of codecs){if(MediaRecorder.isTypeSupported(c)){mime=c;break}}try{cirRec=new MediaRecorder(cirStream,mime?{mimeType:mime,videoBitsPerSecond:200000,audioBitsPerSecond:32000}:undefined)}catch(e){try{cirRec=new MediaRecorder(cirStream)}catch(e2){toast('Видео не поддерживается',true);if(cirStream)cirStream.getTracks().forEach(t=>t.stop());cirStream=null;closeM('m-circle');return}}cirRec.ondataavailable=e=>{if(e.data.size>0)cirChunks.push(e.data)};cirRec.onerror=e=>{toast('Ошибка записи',true);cancelCircle()};cirRec.onstop=async()=>{try{const finalMime=mime||cirRec.mimeType||'video/webm';const blob=new Blob(cirChunks,{type:finalMime});if(blob.size>1500000){toast('Кружок слишком большой',true);if(cirStream)cirStream.getTracks().forEach(t=>t.stop());cirStream=null;return}const r=new FileReader();r.onload=async ev=>{const {error}=await sb.from('messages').insert({chat_id:chatId,sender_id:me,kind:'circle',media:ev.target.result});if(error){toast('Ошибка: '+error.message,true);return}await loadM(chatId);renderM()};r.readAsDataURL(blob)}catch(err){toast('Ошибка: '+err.message,true)}if(cirStream)cirStream.getTracks().forEach(t=>t.stop());cirStream=null};cirRec.start();openM('m-circle');cirInt=setInterval(()=>{cirSec++;document.getElementById('circle-timer').textContent=fSec(cirSec);if(cirSec>=15)sendCircle()},1000)}
function sendCircle(){if(cirRec&&cirRec.state==='recording')cirRec.stop();if(cirInt){clearInterval(cirInt);cirInt=null}closeM('m-circle')}
function cancelCircle(){if(cirRec&&cirRec.state==='recording'){cirRec.onstop=null;cirRec.stop()}if(cirStream){cirStream.getTracks().forEach(t=>t.stop());cirStream=null}if(cirInt){clearInterval(cirInt);cirInt=null}closeM('m-circle')}
function toggleStickers(){const p=document.getElementById('sticker-panel');if(p.classList.contains('show')){p.classList.remove('show');return}document.getElementById('attach-panel').classList.remove('show');const g=document.getElementById('sticker-grid');g.innerHTML=STICKERS.map(s=>`<button class="sticker-item" onclick="sendSticker('${s}')">${s}</button>`).join('');p.classList.add('show')}
async function sendSticker(s){document.getElementById('sticker-panel').classList.remove('show');const {error}=await sb.from('messages').insert({chat_id:chatId,sender_id:me,kind:'sticker',content:s});if(error)return toast('Ошибка: '+error.message,true);await loadM(chatId);renderM()}
function openDraw(){openM('m-draw');setTimeout(()=>{const c=document.getElementById('draw-canvas');if(!c||c.dataset.init)return;c.dataset.init='1';c.width=600;c.height=600;drawCtx=c.getContext('2d');drawCtx.fillStyle='#fff';drawCtx.fillRect(0,0,600,600);drawCtx.lineCap='round';drawCtx.lineJoin='round';const start=e=>{drawDrawing=true;drawLastPos=getPos(e,c)};const move=e=>{if(!drawDrawing)return;e.preventDefault();const p=getPos(e,c);drawCtx.strokeStyle=drawColor;drawCtx.lineWidth=parseInt(document.getElementById('draw-size').value)*2;drawCtx.beginPath();drawCtx.moveTo(drawLastPos.x,drawLastPos.y);drawCtx.lineTo(p.x,p.y);drawCtx.stroke();drawLastPos=p};const end=()=>drawDrawing=false;c.addEventListener('mousedown',start);c.addEventListener('touchstart',start,{passive:true});c.addEventListener('mousemove',move);c.addEventListener('touchmove',move,{passive:false});document.addEventListener('mouseup',end);document.addEventListener('touchend',end)},100)}
function getPos(e,c){const rect=c.getBoundingClientRect();const x=e.touches?e.touches[0].clientX:e.clientX;const y=e.touches?e.touches[0].clientY:e.clientY;return{x:(x-rect.left)*(600/rect.width),y:(y-rect.top)*(600/rect.height)}}
function setDrawColor(c){drawColor=c}
function clearDraw(){const c=document.getElementById('draw-canvas');if(!c||!drawCtx)return;drawCtx.fillStyle='#fff';drawCtx.fillRect(0,0,600,600)}
async function sendDraw(){const c=document.getElementById('draw-canvas');if(!c)return;const dataUrl=c.toDataURL('image/jpeg',0.7);if(dataUrl.length>500000)return toast('Слишком большое',true);const {error}=await sb.from('messages').insert({chat_id:chatId,sender_id:me,kind:'photo',media:dataUrl});if(error)return toast('Ошибка: '+error.message);await loadM(chatId);renderM();closeM('m-draw')}
const THEME_COLORS=['#f5f5f7','#e8f5e9','#fff3e0','#fce4ec','#e3f2fd','#f3e5f5','#1a1a1a','#2c2c2e','#1a237e','#4a148c'];
function openThemes(){const el=document.getElementById('theme-colors');if(el){el.innerHTML=THEME_COLORS.map(c=>`<button onclick="setTheme('${c}')" style="width:44px;height:44px;border-radius:50%;background:${c};border:3px solid var(--border);cursor:pointer"></button>`).join('')}openM('m-themes')}
function setTheme(color){if(!chatId)return;localStorage.setItem('chat_theme_'+chatId,color);applyTheme();closeM('m-themes');toast('Тема применена')}
function applyTheme(){if(!chatId)return;const color=localStorage.getItem('chat_theme_'+chatId);const c=document.getElementById('chat-msgs');if(color&&c){c.style.background=color}else if(c){c.style.background=''}}
function resetTheme(){if(chatId)localStorage.removeItem('chat_theme_'+chatId);applyTheme();closeM('m-themes');toast('Тема сброшена')}
function setDisappear(sec){localStorage.setItem('disappear_'+chatId,sec);closeM('m-disappear');toast(sec?'Исчезающие: '+sec+' сек':'Выключено')}
