function openCreateGroup(){selectedMembers=[];groupType='regular';document.getElementById('group-name').value='';document.getElementById('group-add-phone').value='';document.getElementById('gt-regular').style.background='var(--accent)';document.getElementById('gt-regular').style.color='#fff';document.getElementById('gt-family').style.background='';document.getElementById('gt-family').style.color='';renderGroupMembers();openM('m-group')}
function pickGroupType(t){groupType=t;document.getElementById('gt-regular').style.background=t==='regular'?'var(--accent)':'';document.getElementById('gt-regular').style.color=t==='regular'?'#fff':'';document.getElementById('gt-family').style.background=t==='family'?'var(--accent)':'';document.getElementById('gt-family').style.color=t==='family'?'#fff':''}
function renderGroupMembers(){const el=document.getElementById('group-members-list');if(!selectedMembers.length){el.innerHTML='<div style="color:var(--text2);font-size:13px">Никого не добавлено</div>';return}el.innerHTML=selectedMembers.map((u,i)=>`<div class="member-item"><div class="av">${avH(u.avatar)}</div><div style="flex:1;font-size:13px">${esc(u.first_name||'')} ${esc(u.last_name||'')}<br><span style="color:var(--text2);font-size:11px">@${esc(u.nick)}</span></div><button onclick="removeGroupMember(${i})" style="background:none;border:none;color:var(--danger);font-size:18px;cursor:pointer">×</button></div>`).join('')}
function removeGroupMember(i){selectedMembers.splice(i,1);renderGroupMembers()}
async function addGroupMemberByPhone(){if(selectedMembers.length+1>=5)return toast('Максимум 5',true);const ph=normPh(document.getElementById('group-add-phone').value);if(ph.length!==11)return toast('Введите 11 цифр');if(selectedMembers.find(u=>u.phone===ph))return toast('Уже добавлен');try{const {data,error}=await sb.from('profiles').select('*').eq('phone',ph).maybeSingle();if(error)throw error;if(!data)throw new Error('Не найден');if(data.id===me)throw new Error('Это ваш номер');if(data.status!=='approved')throw new Error('Не активен');selectedMembers.push(data);document.getElementById('group-add-phone').value='';renderGroupMembers();toast('Добавлен: @'+data.nick)}catch(e){toast(e.message||'Не найден',true)}}
async function createGroup(){const name=document.getElementById('group-name').value.trim();if(!name)return toast('Введите название');if(selectedMembers.length<2)return toast('Минимум 2 участника',true);if(selectedMembers.length+1>5)return toast('Максимум 5',true);const id=uuid();const members=[me,...selectedMembers.map(u=>u.id)];const {error}=await sb.from('chats').insert({id,type:'group',chat_type:groupType,name,members});if(error)return toast('Ошибка: '+error.message,true);closeM('m-group');await loadAll();toast('Группа создана');await openChat(id)}
async function createChannel(){const name=document.getElementById('channel-name').value.trim();if(!name)return toast('Введите название');const id=uuid();const members=[me];const {error}=await sb.from('chats').insert({id,type:'channel',chat_type:'channel',name,members});if(error)return toast('Ошибка: '+error.message,true);closeM('m-channel');await loadAll();toast('Канал создан');await openChat(id)}
function openChatMenu(){const c=chats.find(x=>x.id===chatId);const isGroup=c&&c.type==='group';const isChannel=c&&c.type==='channel';const menu=document.getElementById('chat-menu-content');let html='<h3 style="text-align:center">Меню чата</h3>';if(isGroup){html+=`<button class="btn sec" style="width:100%;margin-bottom:6px" onclick="openAddMemberToGroup();closeM('m-chatmenu')">➕ Добавить участника</button>`;html+=`<button class="btn sec" style="width:100%;margin-bottom:6px" onclick="openGroupMembers();closeM('m-chatmenu')">👥 Участники</button>`;html+=`<button class="btn sec" style="width:100%;margin-bottom:6px" onclick="openPollCreator();closeM('m-chatmenu')">📊 Создать опрос</button>`;html+=`<button class="btn sec" style="width:100%;margin-bottom:6px" onclick="openThemes();closeM('m-chatmenu')">🎨 Тема чата</button>`;html+=`<button class="btn dgr" style="width:100%" onclick="leaveOrDeleteChat()">🚪 Покинуть группу</button>`}else if(isChannel){html+=`<button class="btn sec" style="width:100%;margin-bottom:6px" onclick="openGroupMembers();closeM('m-chatmenu')">👥 Подписчики</button>`;html+=`<button class="btn dgr" style="width:100%" onclick="leaveOrDeleteChat()">🗑️ Удалить канал</button>`}else{html+=`<button class="btn sec" style="width:100%;margin-bottom:6px" onclick="openThemes();closeM('m-chatmenu')">🎨 Тема чата</button>`;html+=`<button class="btn sec" style="width:100%;margin-bottom:6px" onclick="openDisappear();closeM('m-chatmenu')">⏱️ Исчезающие</button>`;html+=`<button class="btn dgr" style="width:100%" onclick="leaveOrDeleteChat()">🗑️ Удалить чат</button>`}menu.innerHTML=html;openM('m-chatmenu')}
function openDisappear(){if(!chatId)return;openM('m-disappear')}
function openGroupMembers(){if(!chatId)return;const c=chats.find(x=>x.id===chatId);if(!c)return;const members=c.members||[];const names=members.map(id=>{const u=allP.find(x=>x.id===id);return u?('@'+u.nick):'?'}).join('\n');alert((c.type==='channel'?'Подписчики':'Участники')+' ('+members.length+'):\n\n'+names)}
function leaveOrDeleteChat(){if(!chatId)return;if(!confirm('Выйти из чата?'))return;sb.from('chats').delete().eq('id',chatId).then(()=>{closeChat();toast('Удалено')})}
function openAddMemberToGroup(){const c=chats.find(x=>x.id===chatId);if(!c)return;if(c.members.length>=5)return toast('Группа заполнена',true);const phone=prompt('Введите номер:');if(!phone)return;const ph=normPh(phone);if(ph.length!==11)return toast('11 цифр');(async()=>{try{const {data,error}=await sb.from('profiles').select('*').eq('phone',ph).maybeSingle();if(error)throw error;if(!data)throw new Error('Не найден');if(c.members.includes(data.id))throw new Error('Уже в группе');if(c.members.length>=5)throw new Error('Максимум 5');const newMembers=[...c.members,data.id];const {error:e2}=await sb.from('chats').update({members:newMembers}).eq('id',chatId);if(e2)throw e2;c.members=newMembers;toast('@'+data.nick+' добавлен')}catch(e){toast(e.message||'Ошибка',true)}})()}
function openPollCreator(){if(currentChatType!=='group'&&currentChatType!=='family'){toast('Опросы только в группах',true);return}pollOptions=['',''];renderPollOptions();document.getElementById('poll-q').value='';openM('m-poll')}
function renderPollOptions(){document.getElementById('poll-options').innerHTML=pollOptions.map((o,i)=>`<div class="poll-opt-row"><input type="text" value="${esc(o)}" placeholder="Вариант ${i+1}" oninput="pollOptions[${i}]=this.value">${pollOptions.length>2?`<button onclick="removePollOption(${i})">×</button>`:''}</div>`).join('')}
function addPollOption(){if(pollOptions.length>=6)return toast('Максимум 6');pollOptions.push('');renderPollOptions()}
function removePollOption(i){pollOptions.splice(i,1);renderPollOptions()}
async function createPoll(){const q=document.getElementById('poll-q').value.trim();if(!q)return toast('Введите вопрос');const opts=pollOptions.filter(o=>o.trim());if(opts.length<2)return toast('Минимум 2 варианта');const poll={question:q,options:opts,votes:{}};const {error}=await sb.from('messages').insert({chat_id:chatId,sender_id:me,kind:'poll',content:JSON.stringify(poll)});if(error)return toast('Ошибка: '+error.message);closeM('m-poll');await loadM(chatId);renderM()}
